### ISSUE TITLE
Not work

### ISSUE THREAD

**Issue by erkam2002** [bigbrotherteam/BigBrother-0.14.0#1]
Disabling BigBrother v1.5.0-beta
01.03 17:21:23 [Server] Server thread/CRITICAL ClassNotFoundException: "Class ThreadedFactory not found" (EXCEPTION) in "/src/spl/BaseClassLoader" at line 144
01.03 17:21:23 [Server] Server thread/INFO Starting Minecraft: PC server on *:25565 version 1.8
01.03 17:21:23 [Server] INFO Warning: mkdir(): File exists in phar:///imagicalmine_php7.phar/src/pocketmine/plugin/PluginBase.php on line 207
01.03 17:21:23 [Server] Server thread/INFO Enabling BigBrother v1.5.0-beta

**Comment by erkam2002** [comment]
I using Genisys

**Comment by Driesboy** [comment]
ok

**Comment by MrDoni98** [comment]
Genisys Crash Dump Wed Mar 2 05:00:07 CST 2016

Error: Object of class GMP could not be converted to boolean
File: /plugins/BigBrother-0.14.0-master/src/phpseclib/Math/BigInteger
Line: 354
Type: E_RECOVERABLE_ERROR

[354]         if (empty($x) && (abs($base) != 256 || $x !== '0')){

**Comment by Driesboy** [comment]
fixed
