### ISSUE TITLE
New error

### ISSUE THREAD

**Issue by MasterWolf** [bigbrotherteam/BigBrother-0.14.0#12]
![screenshot_2016-03-03-09-01-40](https://cloud.githubusercontent.com/assets/15979343/13487188/913f222e-e120-11e5-851b-2f2f02237d68.png)

**Comment by Driesboy** [comment]
ok

**Comment by MasterWolf** [comment]
@Driesboy need to be fixed

**Comment by Driesboy** [comment]
fixed

**Comment by MasterWolf** [comment]
@Driesboy ok i will test it

**Comment by Driesboy** [comment]
ok
