### ISSUE TITLE
Class ThreadedFactory not found

### ISSUE THREAD

**Issue by Driesboy** [bigbrotherteam/BigBrother-0.14.0#14]
[Server thread/CRITICAL]: ClassNotFoundException: "Class ThreadedFactory not found" (EXCEPTION) in "/src/spl/BaseClassLoader" at line 144

**Comment by Driesboy** [comment]
https://github.com/bigbrotherteam/BigBrother-0.14.0/blob/master/src/shoghicp/BigBrother/network/ServerThread.php#L56

**Comment by Driesboy** [comment]
found problem

**Comment by MasterWolf** [comment]
@Driesboy what about #9 ?

**Comment by Driesboy** [comment]
i hope its fixed

**Comment by MasterWolf** [comment]
@Driesboy now lets fix #9

**Comment by erkam2002** [comment]
Can you fix it?

**Comment by Driesboy** [comment]
no

**Comment by erkam2002** [comment]
why?

**Comment by Varfalomey** [comment]
Please, fix it

**Comment by flaxues** [comment]
Take a look at this :)

https://github.com/PocketMine/PocketMine-SPL/commit/82034afea351b0dbf8b1f9ad41cde9b9de3e1da6

**Comment by flaxues** [comment]
It is removed since 18 september 2015

**Comment by flaxues** [comment]
So If you add that in BigBrother it should "work"

**Comment by Driesboy** [comment]
thx
