### ISSUE TITLE
no join

### ISSUE THREAD

**Issue by Varfalomey** [bigbrotherteam/BigBrother-0.14.0#16]
LoginStart
[21:07:18] [Server thread/INFO]: [/127.0.0.1:37941] logged out due to Login timeout

screens:
http://cs633418.vk.me/v633418835/17236/2AYIqlC6Hik.jpg
http://cs633418.vk.me/v633418835/17240/LIFgJV7FAhs.jpg

i will be test in minecraft 1.8.9, 1.8.8 and 1.8

**Comment by Varfalomey** [comment]
please fix it, thx

**Comment by MasterWolf** [comment]
#9
