### ISSUE TITLE
Adding

### ISSUE THREAD

**Issue by Varfalomey** [bigbrotherteam/BigBrother-0.14.0#17]
Add ThreadedFactory.php in plugin

**Comment by Driesboy** [comment]
yes but idk what it is

**Comment by MasterWolf** [comment]
@Driesboy lol you dhould know what are you doing.

**Comment by Driesboy** [comment]
idk what ThreadedFactory.php is

**Comment by flaxues** [comment]
https://github.com/PocketMine/PocketMine-SPL/commit/82034afea351b0dbf8b1f9ad41cde9b9de3e1da6
