### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by MrDoni98** [bigbrotherteam/BigBrother-0.14.0#20]
Genisys Crash Dump Wed Mar 2 05:00:07 CST 2016
Error: Object of class GMP could not be converted to boolean
File: /plugins/BigBrother-0.14.0-master/src/phpseclib/Math/BigInteger
Line: 354
Type: E_RECOVERABLE_ERROR
[354] if (empty($x) && (abs($base) != 256 || $x !== '0')){

**Comment by Driesboy** [comment]
wow

**Comment by MasterWolf** [comment]
LOL! Why @PeratX is assigned?

**Comment by MasterWolf** [comment]
Its not Genisys fault...

**Comment by Driesboy** [comment]
yes

**Comment by Driesboy** [comment]
but perat can fix this

**Comment by MasterWolf** [comment]
oh thats good

**Comment by MasterWolf** [comment]
Is BigBrother working?

**Comment by Driesboy** [comment]
i dont have this problem
