### ISSUE TITLE
Protocol

### ISSUE THREAD

**Issue by MasterWolf** [bigbrotherteam/BigBrother-0.14.0#3]
Protocol is not 45. Its 42.

**Comment by MasterWolf** [comment]
change plz protocol and translator version to 42 @Driesboy

**Comment by Driesboy** [comment]
ok

**Comment by Driesboy** [comment]
you can change it accept it on your email i have invite you

**Comment by MasterWolf** [comment]
@Driesboy sry i havent got enought time... Can you do it?

**Comment by Driesboy** [comment]
ok

**Comment by MasterWolf** [comment]
@Driesboy but wait i made it.
