### ISSUE TITLE
line 112

### ISSUE THREAD

**Issue by MasterWolf** [bigbrotherteam/BigBrother-0.14.0#6]
line 112 still not fixed!

**Comment by Driesboy** [comment]
give me the error

**Comment by Driesboy** [comment]
and protocol is 45

**Comment by Driesboy** [comment]
see https://github.com/iTXTech/Genisys/blob/master/src/pocketmine/network/protocol/Info.php#L33

**Comment by MasterWolf** [comment]
@Driesboy for php 7 its 45 but for php 5 its 42

**Comment by MasterWolf** [comment]
https://github.com/bigbrotherteam/BigBrother-0.14.0/issues/2

**Comment by MasterWolf** [comment]
fixed
